Controle.Estoque/Models/Unidade.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Controle.Estoque.Models
{
    public class Unidade
    {
        public int Id { get; set; }
        public string Sigla { get; set; }
        public string Descricao { get; set; }
        public DateTime DataInclusao { get; set; }
        public string Status { get; set; }
    }
}

Controle.Estoque/Controllers/EstoqueController.cs
using Controle.Estoque.Data;
using Controle.Estoque.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Controle.Estoque.Controllers
{
    [Authorize]
    public class EstoqueController : Controller
    {
        private ApplicationDbContext _context;

        public EstoqueController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(string searchProd = null)
        {
            var model = new List<Produto>();


            model = string.IsNullOrEmpty(searchProd) ? _context.Produtos.Where(t => t.Status == "D").ToList()
                                                      : _context.Produtos.Where(t => t.Status == "D" && t.Descricao.Contains(searchProd)).ToList();
            foreach (var item in model)
            {
                item.Categoria = _context.Categorias.FirstOrDefault(t => t.Id == item.CategoriaId);
                item.UnidadeMedida = _context.Unidades.FirstOrDefault(u => u.Id == item.UnidadeId);
            }

            return View(model);
        }
    }
}

Controle.Estoque/Controllers/UnidadesController.cs
using Controle.Estoque.Data;
using Controle.Estoque.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Controle.Estoque.Controllers
{
    [Authorize]
    public class UnidadesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UnidadesController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Create()
        {
            return View(new Unidade());
        }

        [HttpPost]
        public IActionResult Create(Unidade unidade)
        {
            if (ModelState.IsValid)
            {
                unidade.Status = "A";
                unidade.DataInclusao = DateTime.Now;
                _context.Add(unidade);
                _context.SaveChanges();
            }

            return RedirectToAction("Create");
        }
    }
}

Controle.Estoque/Views/Unidades/Create.cshtml
@model Controle.Estoque.Models.Unidade

@{
    ViewData["Title"] = "Novo";
}
<hr />
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div style="margin-top:15px" class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-lg-8">
                            <h2><i class="fas fa-plus-circle"></i><strong>&nbsp; Unidade de Medida</strong></h2>
                        </div>
                    </div>
                </div>
                <div class=" panel-body">
                    <form id="UnidadesForm" name="UnidadesForm" class="form-horizontal" asp-controller="Unidades" asp-action="Create" method="post">

                        <div class="form-group">
                            <label class="col-lg-2 control-label">
                                <strong>Sigla:</strong>
                            </label>
                            <div class="col-lg-1">
                                <input asp-for="Sigla"  class="form-control" required />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-2 control-label">
                                <strong>Categoria:</strong>
                            </label>
                            <div class="col-lg-4">
                                <input asp-for="Descricao"  class="form-control" required />
                            </div>
                        </div>

                        <hr />
                        <div class="form-group">
                            <div class="col-lg-offset-8 text-center">
                                <button type="submit" class="btn btn-success btn-lg">Enviar</button>
                                <a asp-controller="Estoque" asp-action="Index" class="btn btn-danger btn-lg">Cancelar</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>