Controle.Estoque/Models/Categoria.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Controle.Estoque.Models
{
    public class Categoria
    {
        public int  Id { get; set; }
        public string Descricao { get; set; }
        public DateTime DataInclusao { get; set; }
        public string Status { get; set; }
    }
}

Controle.Estoque/Controllers/CategoriasController.cs
using Controle.Estoque.Data;
using Controle.Estoque.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Controle.Estoque.Controllers
{
    [Authorize]
    public class CategoriasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriasController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Create()
        {
            return View(new Categoria());
        }

        [HttpPost]
        public IActionResult Create(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                categoria.Status = "A";
                categoria.DataInclusao = DateTime.Now;
                _context.Add(categoria);
                _context.SaveChanges();
            }

            return RedirectToAction("Create");
        }
    }
}

Controle.Estoque/Controllers/EstoqueController.cs
using Controle.Estoque.Data;
using Controle.Estoque.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Controle.Estoque.Controllers
{
    [Authorize]
    public class EstoqueController : Controller
    {
        private ApplicationDbContext _context;

        public EstoqueController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(string searchProd = null)
        {
            var model = new List<Produto>();


            model = string.IsNullOrEmpty(searchProd) ? _context.Produtos.Where(t => t.Status == "D").ToList()
                                                      : _context.Produtos.Where(t => t.Status == "D" && t.Descricao.Contains(searchProd)).ToList();
            foreach (var item in model)
            {
                item.Categoria = _context.Categorias.FirstOrDefault(t => t.Id == item.CategoriaId);
                item.UnidadeMedida = _context.Unidades.FirstOrDefault(u => u.Id == item.UnidadeId);
            }

            return View(model);
        }
    }
}

Controle.Estoque/Views/Categorias/Create.cshtml
@model Controle.Estoque.Models.Categoria

@{
    ViewData["Title"] = "Novo";
}
<hr />
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div style="margin-top:15px" class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-lg-8">
                            <h2><i class="fas fa-plus-circle"></i><strong>&nbsp; Categoria</strong></h2>
                        </div>
                    </div>
                </div>
                <div class=" panel-body">
                    <form id="CategoriasForm" name="CategoriasForm" class="form-horizontal" asp-controller="Categorias" asp-action="Create" method="post">
                        <div class="form-group">
                            <label class="col-lg-2 control-label">
                                <strong>Categoria:</strong>
                            </label>
                            <div class="col-lg-4">
                                <input  asp-for="Descricao" class="form-control" />
                            </div>
                        </div>

                        <hr />
                        <div class="form-group">
                            <div class="col-lg-offset-8 text-center">
                                <button type="submit" class="btn btn-success btn-lg">Enviar</button>
                                <a asp-controller="Estoque" asp-action="Index" class="btn btn-danger btn-lg">Cancelar</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>