Controle.Estoque/Models/Erro.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Controle.Estoque.Models
{
    [NotMapped]
    public class Erro
    {
        public string Mensagem { get; set; }
    }
}

Controle.Estoque/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Controle.Estoque.Data;
using Controle.Estoque.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Controle.Estoque.Controllers
{
    [Authorize]
    public class ClienteController : Controller
    {
        private readonly ApplicationDbContext _context;
        public IActionResult Index(string searchParam = null)
        {
            var model = new List<Cliente>();
            if(string.IsNullOrEmpty(searchParam))
                model = _context.Clientes.Where(x => x.Status == "A").ToList();
            else
                model = _context.Clientes.Where(x => x.Status == "A" && (x.NomeCliente.Contains(searchParam) || x.Documento == searchParam)).ToList();
            return View(model);
        }
        public ClienteController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Create()
        {
            var estados = _context.Estados.ToList();

            //ViewBag.DropDownEstados = new SelectList(estados,"Sigla","Nome");

            if(estados != null)
                ViewBag.Estados = estados;

            return View(new Cliente());
        }
        [HttpPost]
        public IActionResult Create([Bind("NomeCliente,Documento,Endereco,Cidade,Estado,Pais,Telefone,Email")]Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                cliente.Status = "A";
                cliente.Data_inclusao = DateTime.Now;
                _context.Add(cliente);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Estados = _context.Estados.ToList();
                return View("Create",cliente);
            }

        }
        public IActionResult Delete(int idCliente)
        {
            var cliente = _context.Find<Cliente>(idCliente);
            if (cliente != null)
            {
                cliente.Status = "I";
                cliente.Data_alteracao = DateTime.Now;
                _context.Update(cliente);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public IActionResult Edit([Bind("NomeCliente,Documento,Endereco,Cidade,Estado,Pais,Telefone,Email")]int idCliente)
        {

            var estados = _context.Estados.ToList();

            if (estados != null)
                ViewBag.Estados = estados;

            var cliente = _context.Find<Cliente>(idCliente);
            if (cliente != null)
                return View(cliente);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit([Bind("NomeCliente,Documento,Endereco,Cidade,Estado,Pais,Telefone,Email")]Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                cliente.Data_alteracao = DateTime.Now;
                _context.Update(cliente);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Estados = _context.Estados.ToList();
                return View("Edit", cliente);
            }
        }
        [HttpGet]
        public  IActionResult Details (int idCliente)
        {
            var cliente = _context.Find<Cliente>(idCliente);
            if (cliente != null)
                return View(cliente);
            return RedirectToAction("Index");
        }
    }
}

Controle.Estoque/Controllers/EstoqueController.cs
using Controle.Estoque.Data;
using Controle.Estoque.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Controle.Estoque.Controllers
{
    [Authorize]
    public class EstoqueController : Controller
    {
        private ApplicationDbContext _context;

        public EstoqueController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(string searchProd = null)
        {
            var model = new List<Produto>();


            model = string.IsNullOrEmpty(searchProd) ? _context.Produtos.Where(t => t.Status == "D").ToList()
                                                      : _context.Produtos.Where(t => t.Status == "D" && t.Descricao.Contains(searchProd)).ToList();
            foreach (var item in model)
            {
                item.Categoria = _context.Categorias.FirstOrDefault(t => t.Id == item.CategoriaId);
                item.UnidadeMedida = _context.Unidades.FirstOrDefault(u => u.Id == item.UnidadeId);
            }

            return View(model);
        }
    }
}

Controle.Estoque/Controllers/ProdutosController.cs
using Controle.Estoque.Data;
using Controle.Estoque.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace Controle.Estoque.Controllers
{
    [Authorize]
    public class ProdutosController : Controller
    {
        private readonly ApplicationDbContext _context;
    
        public ProdutosController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Create()
        {
            var categorias = _context.Categorias.Where(t => t.Status == "A").ToList();
            var unidades = _context.Unidades.Where(u => u.Status == "A").ToList();

            if (categorias != null)
                ViewBag.Categorias = categorias;

            if (unidades != null)
                ViewBag.Unidades = unidades;

            return View(new Produto());
        }

        [HttpPost]
        public IActionResult Create(Produto produto)
        {

            var categorias = _context.Categorias.Where(t => t.Status == "A").ToList();
            var unidades = _context.Unidades.Where(u => u.Status == "A").ToList();

            if (categorias != null)
                ViewBag.Categorias = categorias;

            if (unidades != null)
                ViewBag.Unidades = unidades;


            if (ModelState.IsValid)
            {
                produto.Codigo = Guid.NewGuid().ToString("N").ToUpper().Substring(0,8);
                produto.DataInclusao = DateTime.Now;
                produto.Status = "D";
                produto.Cor.ToUpper();

               _context.Add(produto);

                _context.SaveChanges();
                return RedirectToAction("Index", nameof(Estoque));
            }
            else
            {
                categorias = _context.Categorias.Where(t => t.Status == "A").ToList();
                unidades = _context.Unidades.Where(u => u.Status == "A").ToList();

                if (categorias != null)
                    ViewBag.Categorias = categorias;

                if (unidades != null)
                    ViewBag.Unidades = unidades;
                return View("Create", produto);
            }
            
        }

        public IActionResult Detail(int id)
        {
            var categorias = _context.Categorias.Where(t => t.Status == "A").ToList();
            var unidades = _context.Unidades.Where(u => u.Status == "A").ToList();

            if (categorias != null)
                ViewBag.Categorias = categorias;

            if (unidades != null)
                ViewBag.Unidades = unidades;

            var produto = _context.Find<Produto>(id);
            return View(produto);
        }

        public IActionResult Edit(int id)
        {
            var categorias = _context.Categorias.Where(t => t.Status == "A").ToList();
            var unidades = _context.Unidades.Where(u => u.Status == "A").ToList();

            if (categorias != null)
                ViewBag.Categorias = categorias;

            if (unidades != null)
                ViewBag.Unidades = unidades;

            var produto = _context.Find<Produto>(id);

            if (produto == null)
                return RedirectToAction("Index", nameof(Estoque));

            return View(produto);
        }

        [HttpPost]
        public IActionResult Edit(Produto produto)
        {
            if (ModelState.IsValid)
            {
                _context.Update(produto);
                _context.SaveChanges();
                return RedirectToAction("Index", nameof(Estoque));

            }
            else
            {
                var categorias = _context.Categorias.Where(t => t.Status == "A").ToList();
                var unidades = _context.Unidades.Where(u => u.Status == "A").ToList();

                if (categorias != null)
                    ViewBag.Categorias = categorias;

                if (unidades != null)
                    ViewBag.Unidades = unidades;
                return View("Edit", produto);
            }
        }

        public IActionResult ConfirmDelete(int id)
        {
            var model = _context.Produtos.FirstOrDefault(t => t.Id == id);
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(int id, int qtde)
        {
            var item = _context.Produtos.FirstOrDefault(t => t.Id == id);

            if (qtde > item.EstoqueAtual)
                return View(nameof(Erro), new Erro { Mensagem = "Você está tentando excluir mais do que o estoque de itens desse produto" });

            if (item != null &&  qtde == item.EstoqueAtual)
                item.Status = "E"; //Excluído

            if (item != null && (qtde <= item.EstoqueAtual))
                item.EstoqueAtual -= qtde;

            _context.Update(item);

            _context.SaveChanges();
           
            return RedirectToAction("Index", nameof(Estoque));
        }

    }
}

Controle.Estoque/Controllers/VendasController.cs
using Controle.Estoque.Data;
using Controle.Estoque.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Controle.Estoque.Controllers
{
    [Authorize]
    public class VendasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VendasController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(string searchVenda = null)
        {
            var model = new List<Venda>();
            if(string.IsNullOrEmpty(searchVenda))
                model = _context.Vendas.Where(x => x.StatusVenda == "A").ToList();
            else
                model = _context.Vendas.Where(x =>(x.Cliente.NomeCliente.Contains(searchVenda) || x.Produto.Descricao == searchVenda)).ToList();

            foreach (var venda in model)
            {
                venda.Cliente = _context.Clientes.FirstOrDefault(t => t.IdCliente == venda.ClienteId);
                venda.Produto = _context.Produtos.FirstOrDefault(t => t.Id== venda.ProdutoId);
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            var produtos = _context.Produtos.Where(t => t.Status == "D" && t.EstoqueAtual > t.EstoqueMinimo).ToList();
            var unidades = _context.Unidades.Where(u => u.Status == "A").ToList();
            var clientes = _context.Clientes.Where(v => v.Status == "A").ToList();

            if (produtos != null)
                ViewBag.Produtos = produtos;

            if (unidades != null)
                ViewBag.Unidades = unidades;
            if (clientes != null)
                ViewBag.Clientes = clientes;

            return View(new Venda());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create ([Bind("ClienteId,ProdutoId,Quantidade,UnidadeId")]Venda venda)
        {
            Produto produto = null;
            if (ModelState.IsValid)
            {
                produto = new Produto();
                produto = _context.Find<Produto>(venda.ProdutoId);
                if(produto.EstoqueAtual < venda.Quantidade)
                {
                    return View(nameof(Erro), new Erro { Mensagem = "Não há estoque suficiente para essa venda!" });
                }
                venda.DataVenda = DateTime.Now;
                var chars = "0123456789";
                var random = new Random();
                venda.Pedido = new string(Enumerable.Repeat(chars, 7).Select(s => s[random.Next(s.Length)]).ToArray());
                venda.StatusVenda = "A";
                _context.Add(venda);
                produto.EstoqueAtual -= venda.Quantidade;
                _context.Update(produto);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Produtos = _context.Produtos.Where(t => t.Status == "D").ToList();
            ViewBag.Unidades = _context.Unidades.Where(u => u.Status == "A").ToList();
            ViewBag.Clientes = _context.Clientes.Where(v => v.Status == "A").ToList();
            return View("Create",venda); 
        }
        public IActionResult Delete (int idVenda)
        {
            var venda = _context.Find<Venda>(idVenda);
            var produto = _context.Find<Produto>(venda.ProdutoId);
            if(venda != null)
            {
                venda.StatusVenda = "C";
                produto.EstoqueAtual += venda.Quantidade;
                venda.Observacao = "Cancelada as:" + DateTime.Now;
                _context.Update(venda);
                _context.Update(produto);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nameof(Erro), new Erro { Mensagem = "Não foi possivel cancelar venda!" });
        }

    }
}

Controle.Estoque/Views/Shared/Erro.cshtml
@model Controle.Estoque.Models.Erro

@{
    ViewData["Title"] = "Erro";
}

<br />

<div class="container">
    <div class="row">
        <div class="col-lg-2">
            <a asp-controller="Locacao" asp-action="New">Voltar</a>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="alert alert-danger text-danger">
                <h3> <strong>@Model.Mensagem</strong></h3>
            </div>
        </div>
    </div>
</div>

Controle.Estoque/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Controle de Estoque</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/fontawesome-all.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="row">
                    <div class="col-lg-2">
                        <i class="fas fa-cubes fa-3x" style="color:orange"></i>
                    </div>
                    <div class="col-lg-10">
                        <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Controle de Estoque</a>
                    </div>
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Estoque" asp-action="Index"><i class="fa fa-cubes"></i> Estoque</a></li>
                    <li><a asp-controller="Locacao" asp-action="Index"> <i class="fas fa-hands-helping"></i>Locações</a></li>
                    <li><a asp-controller="Vendas" asp-action="Index"> <i class="fas fa-shopping-cart"></i> Vendas</a></li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cadastros  <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a title="Cadastrar novo cliente" asp-controller="Cliente" asp-action="Index"><i class="fa fa-users"></i> Clientes</a></li>
                            <li><a title="Cadastrar novo produto" asp-controller="Produtos" asp-action="Create"><i class="fab fa-codepen"></i> Produtos</a></li>
                            <li><a title="Cadastrar uma nova categoria" asp-controller="Categorias" asp-action="Create"><i class="fa fa-bars"></i> Categorias</a></li>
                            <li><a title="Cadastrar novo unidade de medida" asp-controller="Unidades" asp-action="Create"><i class="fas fa-balance-scale"></i> Unidades </a></li>
                        </ul>
                    </li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Victor & Fechner</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-mask/jquery.mask.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="~/lib/jquery-mask/jquery.mask.min.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>